### ISSUE TITLE
Fix invalid CSS rule within our theme's reset property

### ISSUE THREAD

**Issue by chausknecht** [jwstegemann/fritz2#318]
The following error is thrown from the default theme's reset property:

```JS
unable to insert rule in stylesheet: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '::-moz-focus-inner{border-style:none;padding:0;}'. DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '::-moz-focus-inner{border-style:none;padding:0;}'.
    at _no_name_provided__377.invoke_552 (webpack-internal:///./kotlin/fritz2-kitchensink.js:60604:40)
    at Array.eval (webpack-internal:///./kotlin/fritz2-kitchensink.js:61054:16)
    at eval (webpack-internal:///../../node_modules/stylis/dist/stylis.mjs:68:5957)
    at se (webpack-internal:///../../node_modules/stylis/dist/stylis.mjs:68:5651)
    at Styling.addDynamicCss (webpack-internal:///./kotlin/fritz2-kitchensink.js:60722:7)
    at Styling.resetCss (webpack-internal:///./kotlin/fritz2-kitchensink.js:60714:10)
    at resetCss (webpack-internal:///./kotlin/fritz2-kitchensink.js:60543:27)
    at new Companion_28 (webpack-internal:///./kotlin/fritz2-kitchensink.js:79452:5)
    at Companion_getInstance_27 (webpack-internal:///./kotlin/fritz2-kitchensink.js:79472:7)
    at main (webpack-internal:///./kotlin/fritz2-kitchensink.js:100840:31)
```

### Affected Browsers (add others via browser stack):
- Chrome Desktop ( 89.0.4389.90)
- Opera Desktop (?)

### Not affected Browsers
- Firefox Desktop (86.0.1)

**Comment by jamowei** [comment]
I found in an other [normalize.css](https://github.com/necolas/normalize.css) this rule instead:
![Screenshot_20210318_113220](https://user-images.githubusercontent.com/29158537/111612530-d79f5e00-87dd-11eb-8fa0-82fdab89cf86.png)
So I think `button::-moz-focus-inner{border-style:none;padding:0;}` will fix it!?

**Comment by jamowei** [comment]
After researching a bit I found out that this a general problem with inserting Firefox specific css commands by using `CSSStyleSheet.insertRule()` function in Chrome. The only solution is to fail silently by catching the error to avoid the error messages in the Chrome console. Chrome ignores this rules anyway.

https://github.com/cssinjs/jss/issues/1087

**Comment by mkempa-np** [comment]
The Firefox specific property `:-moz-focusring{outline:1px dotted ButtonText}` creates an unwanted dotted outline around a component, in this case an input field. 

This can be prevented if said property is not used or overriden by `:-moz-focusring{outline: none}`. What is the best solution for this issue?

<img width="496" alt="InputField_unwanted_outline" src="https://user-images.githubusercontent.com/74660896/111997774-aa271d00-8b1b-11eb-9174-326dad972504.png">
