### ISSUE TITLE
Consider KSP as substitute for KAPT for automatic lenses generation

### ISSUE THREAD

**Issue by chausknecht** [jwstegemann/fritz2#542]
## Motivation

- KAPT relies on JDK internals, that are deprecated since Java 9 (!)
- ...so nowadays it has [stopped working](https://youtrack.jetbrains.com/issue/KT-45545) with Java >= 16
- our KAPT implementation uses an deprecated API call `TypeElement.asClassName()` -> we have not figured out how to fix that!

-> we need a new solution!

## KSP to the rescue

[KSP](https://kotlinlang.org/docs/ksp-overview.html#symbolprocessorprovider-the-entry-point) appears to be the "new" default mechanism for writing Kotlin compiler plugins. So it seems quite natural and rational to build the new lenses generating upon this tool.

Our [unit testing plugin](https://github.com/tschuchortdev/kotlin-compile-testing#kotlin-symbol-processing-api-support) for lenses generation works also with KSP already.

## See also
- #301 (new API proposals)
- #480
- #497

**Comment by chausknecht** [comment]
The change from KAPT to KSP should be "invisible" to the client!

But as there are some issues related to the code generation, we should definitly have the new approach of lenses location in mind! Would be pointless to invest work into KSP, if the desired dropping of the `L`-object is not achieveable with KSP.

## Transition Proposal
That said, here is some proposal that enables a smooth transition from the current state to the KSP based generation combined with the ideas from #301.

- check whether the `@Lenses` annoted data class has a companion object
- if it has -> "new" lenses generation based upon the companion object (could include also #480 and #497)
- if there is no companion object -> rely on "old" way of code generation with `L` object! 
  - Do not introduce new features into this way of doing
  - print out deprecation warning during compile process
  - annotate `L` object with `Deprecated` annotation so client will be informed about future removal and could start moving to comapion object based solution

After some major version break, 
- drop `L` object generation
- enforce need for companion object -> produce compiler error in that case so client has less pain to fix this

## Problems
This proposal makes the strong assumption, that there was no companion object within client's code until now! If a client already has used the companion object before the implementation of the new approach, he will definitly get compiler errors, as there would be no `L`-object lenses for his code anymore!

-> this could be fixed with an additional annotation for the companion object though. Would be needed only until we drop the "old" `L`-object based way. We even could reuse `Lenses` of define some `WithLenses` annotation. A different name would allow to mark this annotation as deprecated later on though!

## Example
```kotlin
// client uses old approach
@Lenses
data class Person(val name: String, val role: String)
// -> no companion object found -> keep generating `L`-object based lense with `Deprecated` annotation

// client uses old approach but had already some companion object
// Reminder: Client still uses `L.Person.name` within his code!
@Lenses
data class Person(val name: String, val role: String) {
    companion object {
        // some code
    }
}
// -> no annotation found on companion object -> keep generating `L`-object based lense with `Deprecated` annotation

// client uses new approach
@Lenses
data class Person(val name: String, val role: String) {
    @WithLenses companion object
}
// -> generate lenses as extension of companion object ("new" way)
```

**Comment by jillesvangurp** [comment]
I tried updating my fritz2 project to 1.6.0. I now get the error below. Downgrading to 1.5.31 works. 

I wasn't expecting this to work; merely hoping. But it would be nice to switch to ksp; also from a performance point of view. 

I've actually been using buildLens a lot because we have a multi platform client with model classes I can't use the annotation processor for anyway. Not horrible and probably could be a bit nicer with some DSL support. I've never really liked code generation; always ends up adding complexity and build performance issues.


```
e: warning: Supported source version 'RELEASE_8' from annotation processor 'org.jetbrains.kotlin.kapt3.base.ProcessorWrapper' less than -source '17'
e: java.lang.IllegalStateException: Should not be called!
        at org.jetbrains.kotlin.types.ErrorUtils$1.getPackage(ErrorUtils.java:94)
        at org.jetbrains.kotlin.descriptors.DescriptorUtilKt.resolveClassByFqName(descriptorUtil.kt:24)
        at org.jetbrains.kotlin.resolve.checkers.ExperimentalUsageChecker$Companion.checkCompilerArguments$checkAnnotation(ExperimentalUsageChecker.kt:340)
        at org.jetbrains.kotlin.resolve.checkers.ExperimentalUsageChecker$Companion.checkCompilerArguments(ExperimentalUsageChecker.kt:363)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:114)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:253)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:100)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:58)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:170)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1618)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by chausknecht** [comment]
@jillesvangurp Thx for sharing your experiences!

We are actually already working on KSP support (there is a branch with kinda working first implementation, though no PR yet). We still have to evaluate a bit, towards which API variation we would like to go: with `L` object or rather with `companion`-object. We currently tend to the latter, but both have adavantages and limititations - the typical tradeoffs we have to choose from.

Our first impression is that the build speed with KSP increases a lot compared to KAPT! So perhaps you will give it a try then? ;-)

We are working hard on several topics right now to add the last important features into the core, replace KAPT by KSP and harmonize and stabilize some internal API towards a 1.0 release of fritz2 in the next months. So stay tuned :-)

**Comment by jillesvangurp** [comment]
Ah amazing. Would be happy to give it a try once you have some jars to try.
